# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Stacki Documentation
email: joe.kaiser@teradata.com
description: > # this means to ignore newlines until "baseurl:"
        Stacki Documentation
baseurl: "" # the subpath of your site, e.g. /blog
name: "Teradata"
author: "Teradata"
author_url: "https://teradata.com"
url: "https://github.com/teradta/stacki-wiki" # the base hostname & protocol for your site, e.g. http://example.com
tagline: "Install all your base."
#quiet: true
#detach: true

twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

#theme: jekyll-theme-cayman

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - CI_Scripts
  - stacki-wiki
  - vendor
  - content
